### ISSUE TITLE
Aproval of standard proposal for viadeSpec

### ISSUE THREAD

**Issue by luispc1998** [Arquisoft/viade_en2a#107]
Pod Management {#intro}
=====================

It is crucial for the interoperability that we handle the POD data in the same way. Here is a proposal of what we can do.

## File format ##
For the file format we can use JSON-LD, we have used JSON along the degree and we are very familiar with it, 
it won't be a problem to handle that in the application, in fact Javascript facilitates that task with the built-in object "JSON".

### File example ###
What comes next is an example of the **minimun** data that should be stored in the pod with the JSON-LD. More data could be added by our apps,
but at least this should be there. 

_If the minimun data if wanted to be modified, for instance adding "Elevation" to the points, which would be something
quite common, then follow the repo rules to propose a change._

In the example provided, a route has name, description, points, comments and resources. Those two are references, since they may be in other PODs.

The example (if any error is seen in the context, please point it out):

<pre class="include">path: jsonldExample.json</pre>

## Directory hierarchy in the POD ##
Not only we need to state what information should be in the pod, but also where it is located.

We proposed a "viade" folder in the root of the pod, and inside it three folders: routes, comments, resources. This could be more visual.

<pre>

viade/

		routes/

			example.jsonld
			example2.jsonld

		comments/

			comment1.txt
			comment2.txt

		resources/

			foto.jpg
			image.png
			video.mp4

</pre>

### Comments and resources ###
These two are thought to be in the pod of the user that truly owns them, therefore, a user will have in its pod comments and resources that will 
be referenced from other routes (it is a graph, the file will be in many places)

We are considering two different folders even though they are just references because the way we would treat them, we may even not display those two groups
at the same time.

## How to share ##
The simplest idea for this seems to handle the permissions of the route files and when sharing a route give the "reciever" permissions to read the route file.

**Comment by Angelixus** [comment]
If the minimun data if wanted to be modified, for instance adding "Elevation" to the points, which would be something
quite common, then follow the repo rules to propose a change.

This has a weird wording

**Comment by luispc1998** [comment]
For making any modification to this proposal just follow the repository rules. A change could be for instance:  "Add 'Elevation' to the Points".

Does that sound better?

**Comment by Angelixus** [comment]
> For making any modification to this proposal just follow the repository rules. A change could be for instance: "Add 'Elevation' to the Points".
> 
> Does that sound better?

I think so

**Comment by luispc1998** [comment]
Posted and commented in viade spec.
