### ISSUE TITLE
Error popup related to the POD storage

### ISSUE THREAD

**Issue by Raulpemol** [Arquisoft/viade_en2a#219]
This bug prevents the user from creating the notifications.json file and giving permissions to the settings.ttl file when the POD is initially empty and it also breaks the sharing functionality. Although you can still see the routes previously shared to you, you are no longer able to share anyone. Notifications still arrive correctly.

Steps:
1. Log in to Viade
2. The pop ups appear
3. Go to one of your routes
4. Try to share it
5. Open the browser console and see an error
6. If you open the viade/routes/[route], the user to which it was shared does not have read permission

Those pop ups should not appear and neither the error messages in the console. The route app should give permissions to the user over that route.

**Comment by sarav22** [comment]
It's solved now
