### ISSUE TITLE
Retrieve friend info from the pod.

### ISSUE THREAD

**Issue by sarav22** [Arquisoft/viade_en2a#73]
event.preventDefault();
    const profileDoc = await fetchDocument(webId);
    const profile = profileDoc.getSubject(webId);
    const friends = profile.getAllRefs(foaf.knows);
    console.log(friends);//array with the webIds
    friends.forEach(async (friend) => {
      const friendProfile =await profileDoc.getSubject(friend);
      console.log(friendProfile.getString(foaf.name));
    });    
  
In this method we are trying to get the name from each friend we have in the pod. We are able to retrieve the webIds of the friends but not their name or any other information. It does not find neither literals nor references.

**Comment by pglez82** [comment]
With this code I was able to retrieve friend names:


```
async function getFriendsName(webId) {
  const webIdDoc = await fetchDocument(webId);
  const profile = webIdDoc.getSubject(webId);
  const friends = profile.getAllRefs('http://xmlns.com/foaf/0.1/knows');
  friends.forEach(async (friend) => {
    const friendDoc =await fetchDocument(friend);
    const friendProfile = friendDoc.getSubject(friend);
    console.log(friendProfile.getString('http://xmlns.com/foaf/0.1/name'));
  });    
}
```
I don't know if there is an easier way but what you where missing was fetching each friend's profile (where the name is stored).

**Comment by Raulpemol** [comment]
W can use the foaf library to simplify the code, but your solution works perfectly fine. Thank you.
